# Generated by Django 3.2.6 on 2021-08-17 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0002_measuressettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentMeasures',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='Devices',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='Measures',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='Devices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrek.customerdata'),
        ),
        migrations.AddField(
            model_name='devicemeasures',
            name='Measures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrek.devicedata'),
        ),
        migrations.AddField(
            model_name='devicemeasures',
            name='measure_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='Process_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
