# Generated by Django 3.2.6 on 2021-08-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0003_auto_20210817_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='Devices',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='devicemeasures',
            old_name='Measures',
            new_name='Device',
        ),
    ]
