# Generated by Django 3.2.6 on 2021-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0005_auto_20210817_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuressettings',
            name='Measures_delay_seconds',
            field=models.FloatField(),
        ),
    ]
