# Generated by Django 3.2.6 on 2021-08-19 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0007_alter_devicemeasures_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemeasures',
            name='Process_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
