# Generated by Django 3.2.6 on 2021-08-19 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0008_alter_devicemeasures_process_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('code', models.IntegerField()),
                ('address', models.CharField(max_length=1024)),
                ('contacts', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=64)),
                ('additionalInfo', models.CharField(max_length=1024, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrek.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurePoint', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('measures', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrek.device')),
            ],
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='devicemeasures',
            name='Device',
        ),
        migrations.DeleteModel(
            name='CustomerData',
        ),
        migrations.DeleteModel(
            name='DeviceData',
        ),
        migrations.DeleteModel(
            name='DeviceMeasures',
        ),
    ]
