# Generated by Django 3.2.6 on 2021-08-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0009_auto_20210819_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measures', models.JSONField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='measuressettings',
            old_name='Measures_count',
            new_name='measures_count',
        ),
        migrations.RenameField(
            model_name='measuressettings',
            old_name='Measures_delay_seconds',
            new_name='measures_delay_seconds',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='device',
            name='additionalInfo',
        ),
        migrations.RemoveField(
            model_name='measurepoint',
            name='measures',
        ),
        migrations.RemoveField(
            model_name='measuressettings',
            name='Vitrek_IP',
        ),
        migrations.RemoveField(
            model_name='measuressettings',
            name='Vitrek_Port',
        ),
        migrations.AddField(
            model_name='measurepoint',
            name='current_type',
            field=models.CharField(choices=[('AC_50_Hz', 'AC 50 Hz'), ('DC', '='), ('AC_0.1_Hz', 'AC 0.1 Hz')], default='AC_50_Hz', max_length=64),
        ),
        migrations.AddField(
            model_name='measuressettings',
            name='vitrek_IP',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='measuressettings',
            name='vitrek_Port',
            field=models.PositiveIntegerField(default='10733'),
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_point', models.FloatField(default=0)),
                ('acv', models.FloatField()),
                ('dcv', models.FloatField()),
                ('frequency', models.FloatField()),
                ('pk_pk', models.FloatField()),
                ('crf', models.FloatField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrek.measurepoint')),
            ],
        ),
    ]
