# Generated by Django 3.2.6 on 2021-08-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0010_auto_20210827_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measures',
            name='measure_point',
        ),
    ]
