# Generated by Django 3.2.6 on 2021-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0012_alter_currentmeasure_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmeasure',
            name='measures',
            field=models.JSONField(default=[]),
        ),
    ]
