# Generated by Django 3.2.6 on 2021-08-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0013_alter_currentmeasure_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmeasure',
            name='measures',
            field=models.JSONField(default={'data': []}),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrek.customer'),
        ),
        migrations.AlterField(
            model_name='measurepoint',
            name='current_type',
            field=models.CharField(choices=[('DC', 'DC'), ('AC_50_Hz', 'AC 50 Hz'), ('AC_0.1_Hz', 'AC 0.1 Hz')], default='AC_50_Hz', max_length=64),
        ),
        migrations.AlterField(
            model_name='measurepoint',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrek.device'),
        ),
    ]
