# Generated by Django 3.2.6 on 2021-08-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0015_auto_20210830_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasuresSettings',
            new_name='MeasuresSetting',
        ),
    ]
