# Generated by Django 3.2.6 on 2021-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0016_rename_measuressettings_measuressetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurepoint',
            old_name='measurePoint',
            new_name='measure_point',
        ),
        migrations.AddField(
            model_name='currentmeasure',
            name='current_type',
            field=models.CharField(default='AC', max_length=64),
        ),
        migrations.AddField(
            model_name='currentmeasure',
            name='measure_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurepoint',
            name='current_type',
            field=models.CharField(max_length=64),
        ),
    ]
