# Generated by Django 3.2.6 on 2021-09-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrek', '0017_auto_20210830_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuressetting',
            name='divider',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='measuressetting',
            name='emr',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='measuressetting',
            name='protocol_folder',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='currentmeasure',
            name='current_type',
            field=models.CharField(default='AC_50_Hz', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='measuressetting',
            name='measures_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='measuressetting',
            name='measures_delay_seconds',
            field=models.FloatField(default=0.1),
        ),
    ]
